# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "log4r", "~>1.1.0"

gem "rubyforge", ">=2.0.4", :group => [:development, :test]
gem "minitest", "~>4.5", :group => [:development, :test]
gem "rdoc", "~>3.10", :group => [:development, :test]

# vim: syntax=ruby
